storefront/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root  'items#index'
get   '/items' =>   'items#index', as: :items
get   '/items/new' =>   'items#new', as: :new_item

end

storefront/app/models/address.rb
class Address < ApplicationRecord

belongs_to :user

end

storefront/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

storefront/app/models/item.rb
class Item < ApplicationRecord

has_many :orders

end

storefront/app/models/order.rb
class Order < ApplicationRecord

belongs_to :item
belongs_to :user

end

storefront/app/models/user.rb
class User < ApplicationRecord

has_many :addresses
has_many :orders

end

storefront/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

storefront/app/controllers/items_controller.rb
class ItemsController < ApplicationController
    # displays all items
    def index
        @items = Item.all # .order id:
    end

    # creates a new item
    def new
        @items = item.new
    end

    def create
        @item = item.new
        @item.title = [:title]
        @item.category = params[:item][:category]
        @item.description = params[:item][:description]
        @item.price = params[:item][:price]
        @item.save
        redirect_to root_path
    end
end

storefront/app/helpers/application_helper.rb
module ApplicationHelper
end

storefront/app/views/items/index.html.erb
<div class="jumbotron" background-image: "/images/receipts.jpg" ; height:300px;>
    <h1>CRUD-dy Storefront</h1>
    <ul class="nav nav-pills" role="tablist">
        <li role="presentation" class="active">
            <div class="btn-group btn-lg">
                <button type="button" class="btn btn-primary btn-lg">
                    <span class="glyphicon glyphicon-upload" aria-hidden="true" aria-expanded="false">
                        <%= link_to "", new_item_path %>
                    </span>
                </button>
                <button type="button" class="btn btn-lg" aria-haspopup="true" aria-expanded="false"><%= link_to "New item", new_item_path %>
                </button>
            </div>
    </ul>
</div>
<div>
    <table class="table table-condensed table-striped table-hover">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Category</th>
            <th>Description</th>
            <th>Price</th>
            <th>Quantity Sold</th>
        </tr>
        <tbody>
            <% @items.each do |item|%>
            <tr>
                <td><%= item.id%></td>
                <td><%= item.title%></td>
                <td><%= item.category%></td>
                <td><%= item.description%></td>
                <td><%= number_to_currency(item.price/100.to_f)  %></td>
                <td><%= item.orders.sum(:quantity)%></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

storefront/app/views/items/new_item.html.erb
<div class="jumbotron" background-image: "/images/receipts.jpg" ; height:300px;>
    <h1>CRUD-dy Storefront</h1>

</div>

<%= form_for @item do |lindy| %>
<% end %>
<div>
    <%= lindy.label :title %>
    <%= lindy.text_field :title %>
    <%= lindy.label :category %>
    <%= lindy.text_field :category %>
    <%= lindy.label :discription %>
    <%= lindy.text_area :discription %>
</div>
<div>
    <%= lindy.label :price %>
    <%= lindy.text_field :price %>
</div>
<%= lindy.submit %>
</div>

storefront/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Striped</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class='container'>
        <%= yield %>
    </div>
  </body>
</html>